server.port=9090

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.sql.init.mode=always
spring.main.banner-mode=off
spring.main.log-startup-info=false

logging.level.ru.practicum.shareit=WARN
#logging.level.ru.practicum.shareit.item.ItemController=DEBUG
#logging.level.ru.practicum.shareit.item.ItemService=DEBUG
#logging.level.ru.practicum.shareit.request.ItemRequestService=DEBUG
#logging.level.ru.practicum.shareit.booking.BookingService=DEBUG

logging.level.org.springframework.orm.jpa=WARN
logging.level.org.springframework.transaction=WARN
logging.level.org.zalando.logbook=TRACE

spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/shareit
spring.datasource.username=vxuser
spring.datasource.password=vxpasswd
